version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysq
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 13306:3306
